development:
  adapter: postgresql
  encoding: unicode
  database: ads_development
  pool: 5
  timeout: 5000
  username: "your_username"
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ads_test
  pool: 5
  timeout: 5000
  username: "your_username"
  password: "your_password"
